{{ config(materialized='table') }}
with data as (select Destination,
count(DISTINCT case when  statutReservation = 'Ferme' then   NumeroDossier end ) as total_dossier_ferme,
count( DISTINCT case when  CanalRegroupe = 'TO Prod.' then   NumeroDossier end ) as To_prod,
count( DISTINCT case when  CanalRegroupe = ' Group & Collect.' then   NumeroDossier end ) as Group_collect,
count( DISTINCT case when  CanalRegroupe = 'Franchised' then   NumeroDossier end ) as Franchised,
count( DISTINCT case when  CanalRegroupe = 'Internet' then   NumeroDossier end ) as Internet,
count( DISTINCT case when  CanalRegroupe = 'Owned' then   NumeroDossier end ) as Owned,
count( DISTINCT case when  CanalRegroupe = 'Third Party' then   NumeroDossier end ) as Third_party, 
count( DISTINCT case when  CanalRegroupe = 'Call Center' then   NumeroDossier end ) as Call_center,
count( DISTINCT case when  CanalRegroupe = 'Non Renseigné' then   NumeroDossier end ) as Non_renseigne,
count( DISTINCT case when  ID_EMAIL_MD5 is null then   NumeroDossier end ) as clients_non_identifies, 
count( DISTINCT case when  ID_EMAIL_MD5 is not null  then   NumeroDossier end ) as clients_identifies,
round(SAFE_DIVIDE(sum(safe_cast(CaBrut as FLOAT64)) , count(distinct  NumeroDossier)),2) as panier_moy,
round(AVG(DATE_DIFF(cast(DateDepart as Date),cast(DateReservation as Date), day)),2) as delai_achat,
round(AVG(DATE_DIFF(cast(DateRetour as Date), cast(DateDepart as Date), day)),2) as moy_dure_sejour,  
count( DISTINCT case when  TypeProduit = 'Sejour Balneaire' then   NumeroDossier end ) as  Sejour_Balneaire,
count( DISTINCT case when  TypeProduit = 'Circuit' then   NumeroDossier end ) as  Circuit,
count( DISTINCT case when  TypeProduit = 'Vols secs' then   NumeroDossier end ) as  Vols_secs,
count( DISTINCT case when  TypeProduit = 'Sejour_Neige' then   NumeroDossier end ) as  Sejour_Neige,
count( DISTINCT case when  TypeProduit = 'Sejour Ville' then   NumeroDossier end ) as  Sejour_Ville,
count( DISTINCT case when  TypeProduit = 'Sejour Nature' then   NumeroDossier end ) as  Sejour_Nature,
count( DISTINCT case when  TypeProduit = 'Autotour' then   NumeroDossier end ) as  Autotour,
count( DISTINCT case when  TypeProduit = 'Croisiere' then   NumeroDossier end ) as   Croisiere,
round(AVG( NbrClients ),2) as pax_moy,
round(sum(NbrAdultes) / sum(case when NbrEnfants >0 then NbrEnfants end),2) as ratio_Adultes_enfants,
count( DISTINCT case when  GroupeMarketingCircuit = 'Decouvrir' then   NumeroDossier end ) as Decourir,
count( DISTINCT case when  GroupeMarketingCircuit = 'CONNAISSEUR' then   NumeroDossier end ) as CONNAISSEUR,
count( DISTINCT case when  GroupeMarketingCircuit = 'APPROFONDIR' then   NumeroDossier end ) as APPROFONDIR,
count( DISTINCT case when  GroupeMarketingCircuit = 'ESSENTIEL' then   NumeroDossier end ) as ESSENTIEl,
count( DISTINCT case when  GroupeMarketingCircuit = 'Séjours Activités' then   NumeroDossier end ) as Sejours_Activites,
count( DISTINCT case when  GroupeMarketingCircuit = 'GRANDEUR NATURE' then   NumeroDossier end ) as GRANDEUR_NATURE,
count( DISTINCT case when  GroupeMarketingCircuit = 'RENCONTRER' then   NumeroDossier end ) as RENCONTRER,
count( DISTINCT case when  GroupeMarketingCircuit = 'ESTHETE' then   NumeroDossier end ) as ESTHETE,
count( DISTINCT case when  GroupeMarketingCircuit = 'HOTELS AUTRES' then   NumeroDossier end ) as HOTELS_Autres,
count( DISTINCT case when  GroupeMarketingCircuit = 'Lookéa' then   NumeroDossier end ) as Lookea,
count( DISTINCT case when  GroupeMarketingCircuit = 'Tours & Circuits' then   NumeroDossier end ) as Tours_Circuit,
count( DISTINCT case when  GroupeMarketingCircuit = 'SENSATIONNEL' then   NumeroDossier end ) as SENSATIONNEL
FROM {{ source('bq_data', 'datamart_V_032022') }} 
where DateRetour >= DateDepart
group by Destination)

select Destination,
total_dossier_ferme,
To_prod,
Group_collect,
Franchised,
Internet,
Owned,
Third_party,
Call_center, 
Non_renseigne,
clients_non_identifies,
clients_identifies, 
panier_moy,
delai_achat,
moy_dure_sejour,
Sejour_Balneaire,
Circuit,
Vols_secs,
Sejour_Neige,
Sejour_Ville,
Sejour_Nature,
Autotour,
Croisiere,
pax_moy,
ratio_Adultes_enfants,
Decourir,CONNAISSEUR,
APPROFONDIR,ESSENTIEl, 
Sejours_Activites,
GRANDEUR_NATURE,
RENCONTRER,ESTHETE,
HOTELS_Autres,Lookea,
Tours_Circuit,SENSATIONNEL,
from data
