version: 2

models:

  - name: stg_crm_data_overview
    description: Does some manipulation on crm data
    columns:
      - name: DateReservation
        description: date de départ voyage TUI
        tests:
          - dbt_expectations.expect_row_values_to_have_recent_data:
              datepart: day
              interval: 3