version: 2

sources:
  - name: bq_data
    schema: 'tui_data_analytics'
    database: tuifrance
    tables:
      - name: datamart_V_032022


  - name: bq_data_erreur
    schema: 'data_2021'
    database: tuifr-221211
    tables:
      - name: product_data



  - name: bq_partoo
    schema: 'Partoo'
    database: tuifrance
    tables:
      - name: business_analytics
      - name: presence_analytics
      - name: review_analytics

  - name: ga_tui_fr
    schema: '105634506'
    database: tuitda-140515
    tables:
      - name: ga_sessions_*

  - name: cdg
    schema: tuifrance
    database: tuitda-140515
    tables:
      - name: new_cdg_report
