version: 2

sources:
  - name: bq_data
    schema: 'tui_data_analytics'
    database: tuifrance
    tables:
      - name: datamart_V_032022


  - name: bq_data_erreur
    schema: 'data_2021'
    database: tuifr-221211
    tables:
      - name: promotion_analysis
      - name: product_data

  - name: bq_partoo
    schema: 'Partoo'
    database: tuifrance
    tables:
      - name: business_analytics
      - name: presence_analytics
      - name: review_analytics

  - name: ga_tui_fr
    schema: '105634506'
    database: tuitda-140515
    tables:
      - name: ga_sessions_*

  - name: cdg
    schema: tuifrance
    database: tuitda-140515
    tables:
      - name: historic_new_cdg

  - name: crm
    schema: tuifrance
    database: tuitda-140515
    tables:
      - name: QT_032_WS_DIGITAL_DATAMART_DOSSIER20221115

  - name: media_data
    schema: tui_france_funnel
    database: tuifrance
    tables:
      - name: funnel_data    

  - name: product
    schema: data_2021
    database: tuifr-221211
    tables:
      - name: product_data          